# Generated by Django 2.2.4 on 2019-08-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190805_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.AddField(
            model_name='post',
            name='context',
            field=models.TextField(default=20190801, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=20190702, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
